version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: taxclearence-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taxclearence-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    profiles:
      - all

  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taxclearence-backend
    ports:
      - 8889:8889
    volumes:
      - ${PWD}/logs:/logs
#    restart: unless-stopped
    environment:
      spring.datasource.url: jdbc:mysql://taxclearence-mysql:3306/taxclearence-db?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      spring.datasource.username: user
      spring.datasource.password: user
      JAVA_TOOL_OPTIONS: -Xss256K -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=128M -Xmx64M
    depends_on:
      - mysql
    links:
      - mysql
    profiles:
      - all

  postgres:
    image: postgres:9.6
    container_name: taxclearence-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:18.0.0-debian-11-r0
    container_name: taxclearence-keycloak
    environment:
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - postgres

  redis:
    image: redis:5.0.3-alpine
    container_name: taxclearence-redis
    ports:
      - 6379:6379

  maildev:
    container_name: taxclearence-maildev
    image: djfarrelly/maildev:1.0.0-rc2
    ports:
      - 9999:80
      - 25

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local